### PR TITLE
Pretty history details

### LINKED ISSUE #99: History information detail unreadable on large changes
I just added a bunch of records to a domain. When I view the change history details for that edit, it is completely unreadable for humans:

image

System is based on CentOS 7, PowerDNS 3.4.8, latest commit of PowerDNS-admin.

### PR DESCRIPTION
**Pull request by jallakim**
Fixes #99.

### CODE REVIEW

**Comment by jallakim** [comment]
The files `custom.css` and `custom.js` had some weird file type or something, so that new lines added to the file got `^M` as carriage return (in stead of '\r' or whatever). I did a `dos2linux` on them, hence, they seem to have been "completely replaced". Only the last few lines were altered, tho.

**Comment by ngoduykhanh** [comment]
Thanks @jallakim. It looks much better with pretty json display. Can we also use the scroll inside the modal incase the list is long?

**Comment by jallakim** [comment]
The scroll outside the modal works pretty much as one inside the modal? At least on my computer in Chrome...

**Comment by jallakim** [comment]
@ngoduykhanh, doesn't seem like it's a good way to set scroll within the modal (modal body). Only way I've found is to set a static height for the modal-box, but that's not really something we want since people have different sized screens. Using % as height is not possible because it's defined by the parent, which, in this case, also contains the content.

**Comment by ngoduykhanh** [comment]
@jallakim : Ok, so let stick with the your design. We can do more adjustment in the future. Thank you very much for your contribution.

**Pull request merged**
