### PR TITLE
Fix OpenID Connect wrong claim name

### PR DESCRIPTION
**Pull request by maximumG**
Linked to issue #713

### CODE REVIEW

**Comment by RoeiGanor** [comment]
tested it in my setup. When a user is created using oidc, the first name is the full name and there is no last name.
First I checked what the oidc userinfo return from the oidc and here is the given object:
`{'sub': 'xxx-111-yyy', 'email_verified': False, 'name': 'test3 test3', 'preferred_username': 'test3', 'given_name': 'test3', 'family_name': 'test3', 'email': 'test3@test3.com'}`
As we can see, the given name and family name are both populated with the needed value.
Then I deleted the user and recreated it using the proposed fix. The user created as expected.
I can also confirm that there were no impact on how the names (first and last name) are displayed in the UI.

**Comment by terbolous** [comment]
Should these variable names maybe be configurable? I can imagine that different oidc providers may name them differently

**Comment by maximumG** [comment]
> Should these variable names maybe be configurable? I can imagine that different oidc providers may name them differently

If they follow the OIDC specification, then it won't be different. Anyway, in case a provider is using non-standard claims, I guess it could be easy to add some form inputs with default to given_name and family_name.

**Comment by ngoduykhanh** [comment]
I think we better have those claim values configurable for flexibility. In my experience, the claims name may differ among providers. Even in self-hosting OIDC, we can have custom claims.

**Comment by maximumG** [comment]
Would it be possible to merge this pull request as well as #717 please ?

**Comment by ngoduykhanh** [comment]
I've merged the #717 . Closing this PR. Thank you, everyone.

**Pull request closed without merging**
