### PR TITLE
Custom Roles

### PR DESCRIPTION
**Pull request by vmarkop**
This PR is an update to #1113, featuring more precise commit messages, and implementing some of the changes requested by the rest of the administrative team, such as an explanatory documentation file.

Hello,
After our short discussion with the community on issue https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1099, we have decided to publish the final result. This PR introduces all the features that are referenced on the last comment of the above issue, including custom non-administrative Roles, and finer control over the existing User and Operator roles.

The upgrade process does not affect existing users or existing Role behaviour.
All users keep their existing Roles, and existing Role behaviour is initially unchanged. Global settings "Allow users to x..." are deprecated, and their new equivalents are initially turned off for the default "User" role.

More information can be found on this [wiki page](https://github.com/gunet/PowerDNS-Admin/wiki/Custom-Roles).

Don't forget to execute flask db upgrade in order to migrate your database!

Developed by [our team](https://github.com/gunet), in collaboration with @kkmanos.

### CODE REVIEW

**Comment by dg410** [comment]
What's the status on the pr?

**Comment by vmarkop** [comment]
> What's the status on the pr?

Hello @dg410,
this PR is in the bugtesting phase. Since it is such a major issue, which introduces breaking changes, we want to make sure that everything is working before merging it in a release. Therefore, any use feedback and/or testing is highly appreciated.

**Comment by aderumier** [comment]
Hi,I'm also interested by this feature

**Comment by gravasio** [comment]
This will be ever supported?

**Pull request closed without merging**
