### PR TITLE
Adding Operator role and Code adjustment

### PR DESCRIPTION
**Pull request by ngoduykhanh**
In this PR:
- Add `Operator` role.
- Adjust ldap group policy to to have Operator role.
- Change the way of setting user role in User Management
- Adjust the code as LGTM.com suggestion
- Add options to allow user to create domain #130
- Fix domain template record modification #346

This PR is to enhance the security which mentioned in #342. PDA will have 3 roles:
- Administrator: Have full access
- Operator: Have full access except: PDNS and Authentication settings. Not able to edit Administrator users.
- User: Have access to granted domain only.

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
This pull request **introduces 1 alert** and **fixes 82** when merging 40cb835b0e8871beb0f95e72c14e4675a2f83db0 into 5e6806cc0f2eb8493f1e92c24fca35086c3b0cd6 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-0b357f91ad05692ca9b9612e1a2532c72f45d095)

**new alerts:**

* 1 for Too few arguments in formatting call

**fixed alerts:**

* 26 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **fixes 82 alerts** when merging 38d1d85a186ff1ebe217d7ff3447f6e61a9c7d09 into 5e6806cc0f2eb8493f1e92c24fca35086c3b0cd6 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-6da74ef09f9a18d490ec82b93f5ccf2d2ef0d781)

**fixed alerts:**

* 26 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **fixes 82 alerts** when merging 3481af149b8a56e21bcfaec1c139f0adfaa0d89c into 5e6806cc0f2eb8493f1e92c24fca35086c3b0cd6 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-855ccb9fbde13df954d49c33c323a7cd33cf76d5)

**fixed alerts:**

* 26 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **fixes 83 alerts** when merging 25083e04316b2cd915d9bd2c2a191dd85aa06a95 into 5e6806cc0f2eb8493f1e92c24fca35086c3b0cd6 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-2898542e6599d1dcd9253200077dbc57ab08d2e2)

**fixed alerts:**

* 27 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **fixes 83 alerts** when merging 26c2b5e16936967e82412c001150187cf08673f9 into c13d616a7f3edd65a4822da0a52eeccf5c7f53bd - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-860a5f71bd5ddcc66d49b1445d1ffddd3b2bdf40)

**fixed alerts:**

* 27 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
Yes, alembic doesn't fully support sqlite, we will get in trouble with ALTER operations and have to do the migration manually.

**Comment by ngoduykhanh** [comment]
This pull request **fixes 83 alerts** when merging 0081adff364c92bde2258ab64fbfcd3373bf067a into c13d616a7f3edd65a4822da0a52eeccf5c7f53bd - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-e15f35a90672b1c5ff21d1569c6f54d74d1b5802)

**fixed alerts:**

* 27 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **fixes 83 alerts** when merging 902e63a64e4d245385be47be52de8b0152cd3905 into c13d616a7f3edd65a4822da0a52eeccf5c7f53bd - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-48478bb18823a0bf6978816bfd887b16ac24629e)

**fixed alerts:**

* 27 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **fixes 83 alerts** when merging cd183c5731a7bb696f25431c18cfc4fa56121658 into c13d616a7f3edd65a4822da0a52eeccf5c7f53bd - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-95f7adb7036deb3e82aa975f4cd394c7ed10898a)

**fixed alerts:**

* 27 for Except block handles &#39;BaseException&#39;
* 18 for Unused import
* 11 for Unused local variable
* 9 for Use of the return value of a procedure
* 5 for Missing variable declaration
* 5 for Unused variable
* 2 for Unreachable code
* 2 for Malformed id attribute
* 1 for Testing equality to None
* 1 for Module imports itself
* 1 for Comparison using is when operands support \_\_eq\_\_
* 1 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tmuncks** [comment]
I think it's perfectly sane to disregard the sqlite backend as a production-type backend, but for development, it's brilliant and IMHO should be supported. At this point, however, it's not possible to create a new, blank sqlite database, because of the ALTER statements in the migration scripts. Is this acceptable? It effectively means sqlite is no longer supported at all.

There might be a solution, if we want to preserve some type of sqlite support:
http://alembic.zzzcomputing.com/en/latest/batch.html

Alembic supports batch mode processing for databases like sqlite. We should be able to work this into the upgrade scripts to actually make it work again.

What's your take on this?

**Comment by ngoduykhanh** [comment]
I heard about that batch mode but haven't ever used it. It is still beta feature of alembic but OK to use for the development purpose i think. I will spend some time to make it work for sqlite and other database.

**Pull request merged**
