### PR TITLE
Create api - resolves #416

### LINKED ISSUE #416: REST-API to manage Zone Records by Accounts - Feature Request
Found a similar feature on powerdns-auth-proxy and DjangoPowerDNS. It would be great if PowerDNS-Admin would expose it's own API key for each zone so that multiple teams could update their own zone records programmatically.

List Records in a zone
Create a New Record
View a specific Record
Edit a specific Record
Delete a specific Record

powerdnsadmin

### PR DESCRIPTION
**Pull request by p53**
Api based on concept of apikeys similar to users, with exception that apikeys cannot be grouped under account. This is quickest implementation which would enable apikeys to create and self-manage domains and isolate apikeys scope

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
Thanks for the contribution. I will take a look in to your PR. Can you also fix the issue raised by LGTM ?

**Comment by p53** [comment]
Flow would be like this, user authenticates with basic auth, if it is admin or user (can create domain), will create domain. With basic auth, admin or user, will create apikey to which he assigns role and in case it has user role he must specify also domains to which apikey has access. Then with apikey can do most of the operations on pdns, depending on rights

**Comment by ngoduykhanh** [comment]
This pull request **introduces 2 alerts** when merging 2bb1e6c6314427c12870c74baa0cf9ca81691de1 into 5ea38a9b6d2e42e7f95f9bae7b3e7fa5411ddc51 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-a6353110d7666c9bf1e7511d38dfb17bf6e03b49)

**new alerts:**

* 2 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **introduces 1 alert** when merging aba8553f89c254f46f678ad71578bc8f52a2eba5 into 5ea38a9b6d2e42e7f95f9bae7b3e7fa5411ddc51 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-604a12c7e063be2bb25a8fe9cb317e0f871465ed)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **introduces 1 alert** when merging 350a23aa61b2714169fc2ca25be58efb67815a8a into 5ea38a9b6d2e42e7f95f9bae7b3e7fa5411ddc51 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-38991b0598ad83270324a56ce9068d6baa4c344f)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ngoduykhanh** [comment]
This pull request **introduces 1 alert** when merging 79571cd0ca934da2bf1602fcb3694dfa89d8cea4 into 7ba9ad68f82b90f018da1af8413e928c84aa1cd5 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-3948c9325a507f3f457911f6b183d554ce943b86)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alebeta90** [comment]
Hello friends,

when this PR will be merge :D looking forward to test it :D

thanks for the great feature

**Comment by p53** [comment]
you can test it, just checkout branch, run docker image docker-compose up, go to UI http://localhost:9191, click to register user, type e.g. user: admin and password: admin, login to UI in settings enable allow domain creation for users and now you can create and manage domains with admin account and also ordinary users

```curl -L -vvv -H 'Content-Type: application/json' -H 'Authorization: Basic YWRtaW46YWRtaW4=' -X POST http://localhost:9191/api/v1/pdnsadmin/zones --data '{"name": "yourdomain.com.", "kind": "NATIVE", "nameservers": ["ns1.mydomain.com."]}'```

YWRtaW46YWRtaW4= -> this is base64 encoded user:password -> admin:admin

```
curl -L -vvv -H 'Content-Type: application/json' -H 'Authorization: Basic YWRtaW46YWRtaW4=' -X POST http://localhost:9191/api/v1/pdnsadmin/apikeys --data '{"description": "masterkey","domains":[], "role": "Administrator"}'```

```curl -L -vvv -H 'Content-Type: application/json' -H 'X-API-KEY: cU5NVnBkdlFjdlp3YVJH' -X GET http://localhost:9191/api/v1/servers/localhost/config```

cU5NVnBkdlFjdlp3YVJH this is base64 encoded apikey which you you got from call to http://localhost:9191/api/v1/pdnsadmin/apikeys

**Comment by alebeta90** [comment]
Hi @p53 ,

but the branch that should i pull is your branch p53:create-api or it is already merge in here?

thanks and all the best

**Comment by alebeta90** [comment]
Hello @p53 ,

I manage to test the API and it is working fine so far I tried:

Creating Zone
Request API-Key
List Zones
Delete Zone

When Delete zones it gives

< HTTP/1.1 204 NO CONTENT

But the record was successfully deleted.

Now im checking if it is possible to update domain zones with records

thanks for such and amazing code

**Comment by p53** [comment]
according specs if no entity is in response it should return 204 on sucessful delete

**Comment by alebeta90** [comment]
Ok i understand,

for the update of a zone, or adding a new record it is already possible I had been trying but without success or it is necessary to add the endpoint /records?

all the best

**Comment by p53** [comment]
i didnt test that but all endpoints which are in powerdns documentation except tsigkeys should be available when using apikey, i will test it today and let you know

**Comment by p53** [comment]
did you try patch request like in this example but also add apikeys to the header for authentication?

**Comment by alebeta90** [comment]
I just perform one try with API-Key headers, others I did with Basic auth. To be able to perform zone update or add record should I use API-key only? also I need to figure out how to organize the json data that is parse by the API.

**Comment by p53** [comment]
yes basic authentication serves only for managing domain and managing apikeys (apikey can have user or admin role, in case of user role you have to specify for to which domains it has access), with apikeys you can do everything powerdns api can do, after authentication it just forwards request to powerdns, https://doc.powerdns.com/md/httpapi/README/ here are examples for powerdns you need to add apikey to headers for authentication

**Comment by p53** [comment]
there is also /swagger endpoint where you can see api specification in json

**Comment by alebeta90** [comment]
I had been following the examples from powerdns API documentation and using the API-key but I always get msg: Not Found, im trying to check what is going on

**Comment by alebeta90** [comment]
I had been trying to different endpoints:

`http://pdnsadmin.company.internal:9191/api/v1/pdnsadmin/zones/example2.com.` this one said msg: NotFound
AND
`http://pdnsadmin.company.internal:9191/api/v1/servers/localhost/zones/example2.com.`  This one said Internal Server Error

**Comment by alebeta90** [comment]
When Internal Server Error appears, this is the log output

powerdns-admin          | [ERROR] Exception on /api/v1/servers/localhost/config [GET]
powerdns-admin          | Traceback (most recent call last):
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
powerdns-admin          |     response = self.full_dispatch_request()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
powerdns-admin          |     rv = self.handle_user_exception(e)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
powerdns-admin          |     reraise(exc_type, exc_value, tb)
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
powerdns-admin          |     raise value
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
powerdns-admin          |     rv = self.dispatch_request()
powerdns-admin          |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
powerdns-admin          |     return self.view_functions[rule.endpoint](**req.view_args)
powerdns-admin          |   File "/powerdns-admin/app/decorators.py", line 191, in decorated_function
powerdns-admin          |     apikey_val = str(base64.b64decode(auth_header), 'utf-8')
powerdns-admin          |   File "/usr/lib/python3.5/base64.py", line 88, in b64decode
powerdns-admin          |     return binascii.a2b_base64(s)
powerdns-admin          | binascii.Error: Incorrect padding

**Comment by p53** [comment]
your error looks like some problem with your apikey encoding

**Comment by p53** [comment]
@alebeta90 

i tried now api key creation and GET on /api/v1/servers/localhost/config and it works without problem:

```
curl -L -vvv -H 'Content-Type: application/json' -H 'Authorization: Basic YWRtaW46YWRtaW4=' -X POST http://localhost:9191/api/v1/pdnsadmin/apikeys --data '{"description": "samekey","domains":[], "role": "Administrator"}'
```

returns

```
[{"description": "samekey", "domains": [], "role": {"name": "Administrator", "id": 1}, "id": 2, "plain_key": "aGCthP3KLAeyjZI"}]
```

and from there plain_key is apikey in plain text, so i base64 encode it in linux cmd line:

```
someuser@somehost:~$echo -n 'aGCthP3KLAeyjZI'|base64
YUdDdGhQM0tMQWV5alpJ
```

and call config endpoint:

```
url -L -vvv -H 'Content-Type: application/json' -H 'X-API-KEY: YUdDdGhQM0tMQWV5alpJ' -X GET http://localhost:9191/api/v1/servers/localhost/config
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9191 (#0)
> GET /api/v1/servers/localhost/config HTTP/1.1
> Host: localhost:9191
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> X-API-KEY: YUdDdGhQM0tMQWV5alpJ
url -L -vvv -H 'Content-Type: application/json' -H 'X-API-KEY: YUdDdGhQM0tMQWV5alpJ' -X GET http://localhost:9191/api/v1/servers/localhost/config
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9191 (#0)
> GET /api/v1/servers/localhost/config HTTP/1.1
> Host: localhost:9191
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> X-API-KEY: YUdDdGhQM0tMQWV5alpJ
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Wed, 27 Feb 2019 07:44:27 GMT
< Connection: close
< Access-Control-Allow-Origin: *
< Content-Length: 19694
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
< Set-Cookie: _csrf_token=6190e46053f03af4a02b1a53c1fb4291cc2ad29d; Expires=Mon, 04-Mar-2019 07:44:27 GMT; Max-Age=432000; Path=/
< Vary: Cookie
< Set-Cookie: session=eyJfY3NyZl90b2tlbiI6IjYxOTBlNDYwNTNmMDNhZjRhMDJiMWE1M2MxZmI0MjkxY2MyYWQyOWQiLCJfcGVybWFuZW50Ijp0cnVlfQ.XHY_2w.NVvepiiL9dPJ4WM76QGOVF4WGz4; Expires=Wed, 27-Feb-2019 07:54:27 GMT; HttpOnly; Path=/
< 
[{"name": "8bit-dns", "type": "ConfigSetting", "value": "no"}, {"name": "allow-axfr-ips", "type": "ConfigSetting", "value": "127.0.0.0/8,::1"}, {"name": "allow-dnsupdate-from", "type": "ConfigSetting", "value": "127.0.0.0/8,::1"}, {"name
": "allow-notify-from", "type": "ConfigSetting", "value": "0.0.0.0/0,::/0"}, {"name": "allow-unsigned-notify", "type": "ConfigSetting", "value": "yes"}, {"name": "allow-unsigned-supermaster", "type": "ConfigSetting", "value": "yes"}, {"n
ame": "also-notify", "type": "ConfigSetting", "value": ""}, {"name": "any-to-tcp", "type": "ConfigSetting", "value": "yes"}, {"name": "api", "type": "ConfigSetting", "value": "yes"}, {"name": "api-key", "type": "ConfigSetting", "value": 
"***"}, {"name": "api-logfile", "type": "ConfigSetting", "value": "/var/log/pdns.log"}, {"name": "api-readonly", "type": "ConfigSetting", "value": "no"}, {"name": "axfr-lower-serial", "type": "ConfigSetting", "value": "no"}, {"name": "ca
che-ttl", "type": "ConfigSetting", "value": "60"}, {"name": "carbon-interval", "type": "ConfigSetting", "value": "30"}, {"name": "carbon-ourname", "type": "ConfigSetting", "value": ""}, {"name": "carbon-server", "type": "ConfigSetting", 
"value": ""}, {"name": "chroot", "type": "ConfigSetting", "value": ""}, {"name": "config", "type": "ConfigSetting", "value": "no"}, {"name": "config-dir", "type": "ConfigSetting", "value": "/etc/pdns"}, {"name": "config-name", "type": "C
onfigSetting", "value": ""}, {"name": "control-console", "type": "ConfigSetting", "value": "no"}, {"name": "daemon", "type": "ConfigSetting", "value": "no"}, {"name": "default-ksk-algorithm", "type": "ConfigSetting", "value": "ecdsa256"}
, {"name": "default-ksk-size", "type": "ConfigSetting", "value": "0"}, {"name": "default-soa-edit", "type": "ConfigSetting", "value": ""}, {"name": "default-soa-edit-signed", "type": "ConfigSetting", "value": ""}, {"name": "default-soa-m
ail", "type": "ConfigSetting", "value": ""}, {"name": "default-soa-name", "type": "ConfigSetting", "value": "a.misconfigured.powerdns.server"}, {"name": "default-ttl", "type": "ConfigSetting", "value": "3600"}, {"name": "default-zsk-algo
rithm", "type": "ConfigSetting", "value": ""}, {"name": "default-zsk-size", "type": "ConfigSetting", "value": "0"}, {"name": "direct-dnskey", "type": "ConfigSetting", "value": "no"}, {"name": "disable-axfr", "type": "ConfigSetting", "val
ue": "no"}, {"name": "disable-axfr-rectify", "type": "ConfigSetting", "value": "no"}, {"name": "disable-syslog", "type": "ConfigSetting", "value": "no"}, {"name": "disable-tcp", "type": "ConfigSetting", "value": "no"}, {"name": "distribu
tor-threads", "type": "ConfigSetting", "value": "1"}, {"name": "dname-processing", "type": "ConfigSetting", "value": "no"}, {"name": "dnssec-key-cache-ttl", "type": "ConfigSetting", "value": "30"}, {"name": "dnsupdate", "type": "ConfigSe
tting", "value": "no"}, {"name": "do-ipv6-additional-processing", "type": "ConfigSetting", "value": "yes"}, {"name": "domain-metadata-cache-ttl", "type": "ConfigSetting", "value": "60"}, {"name": "edns-subnet-processing", "type": "Config
Setting", "value": "no"}, {"name": "entropy-source", "type": "ConfigSetting", "value": "/dev/urandom"}, {"name": "expand-alias", "type": "ConfigSetting", "value": "no"}, {"name": "forward-dnsupdate", "type": "ConfigSetting", "value": "ye
s"}, {"name": "forward-notify", "type": "ConfigSetting", "value": ""}, {"name": "gmysql-activate-domain-key-query", "type": "ConfigSetting", "value": "update cryptokeys set active=1 where domain_id=(select id from domains where name=?) a
nd  cryptokeys.id=?"}, {"name": "gmysql-add-domain-key-query", "type": "ConfigSetting", "value": "insert into cryptokeys (domain_id, flags, active, content) select id, ?, ?, ? from domains where name=?"}, {"name": "gmysql-any-id-query", 
"type": "ConfigSetting", "value": "SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=? and domain_id=?"}, {"name": "gmysql-any-query", "type": "ConfigSetting", "value": "SELECT content,ttl,p
rio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and name=?"}, {"name": "gmysql-basic-query", "type": "ConfigSetting", "value": "SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 a....```
```

also tried to create records:

```
curl -X PATCH -H 'Content-Type: application/json' --data '{"rrsets": [{"name": "test1.yourdomain.com.","type": "A","ttl": 86400,"changetype": "REPLACE","records": [ {"content": "192.0.2.5", "disabled": false} ]},{"name": "test2.yourdomain.com.","type": "AAAA","ttl": 86400,"changetype": "REPLACE","records": [ {"content": "2001:db8::6", "disabled": false} ]}]}' -H 'X-API-Key: YUdDdGhQM0tMQWV5alpJ' http://127.0.0.1:9191/api/v1/servers/localhost/zones/yourdomain.com.
```

and get info about domain:

```
curl -L -vvv -H 'Content-Type: application/json' -H 'X-API-KEY: YUdDdGhQM0tMQWV5alpJ' -X GET http://localhost:9191/api/v1/servers/localhost/zones/yourdomain.co[34/1188]
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9191 (#0)
> GET /api/v1/servers/localhost/zones/yourdomain.com HTTP/1.1
> Host: localhost:9191
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> X-API-KEY: YUdDdGhQM0tMQWV5alpJ
> 
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Wed, 27 Feb 2019 07:59:42 GMT
< Connection: close
< Access-Control-Allow-Origin: *
< Content-Length: 983
< Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Permitted-Cross-Domain-Policies: none
< X-Xss-Protection: 1; mode=block
< Vary: Cookie
< Set-Cookie: session=eyJfcGVybWFuZW50Ijp0cnVlfQ.XHZDbg.kvkPtxqQNfGK39DMcrCGxu_409w; Expires=Wed, 27-Feb-2019 08:09:42 GMT; HttpOnly; Path=/
< 
* Closing connection 0
{"account": "", "api_rectify": false, "dnssec": false, "id": "yourdomain.com.", "kind": "Native", "last_check": 0, "masters": [], "name": "yourdomain.com.", "notified_serial": 0, "nsec3narrow": false, "nsec3param": "", "rrsets": [{"comments": [], "name": "test2.yourdomain.com.", "records": [{"content": "2001:db8::6", "disabled": false}], "ttl": 86400, "type": "AAAA"}, {"comments": [], "name": "test1.yourdomain.com.", "records": [{"content": "192.0.2.5", "disabled": false}], "ttl": 86400, "type": "A"}, {"comments": [], "name": "yourdomain.com.", "records": [{"content": "a.misconfigured.powerdns.server. hostmaster.yourdomain.com. 2019022702 10800 3600 604800 3600", "disabled": false}], "ttl": 3600, "type": "SOA"}, {"comments": [], "name": "yourdomain.com.", "records": [{"content": "ns1.mydomain.com.", "disabled": false}], "ttl": 3600, "type": "NS"}], "serial": 2019022702, "soa_edit": "", "soa_edit_api": "DEFAULT", "url": "/api/v1/server
s/localhost/zones/yourdomain.com."}
```

**Comment by p53** [comment]
that error messages could be more friendly, i will look at it

**Comment by p53** [comment]
@alebeta90 

i compiled all above to README, hopefully it will help

**Comment by alebeta90** [comment]
Hi @p53 thanks for the explanation,

my error was simple, I misunderstood the api_plain as being already encoded. Now I encoded to base64 and it is working perfectly. I will keep testing. And sharing my experience using the API.

Another question, it is possible to use your branch p53:create-api in production? or when it will be merge with the master branch?

thanks

**Comment by p53** [comment]
i don't have rights to merge

@ngoduykhanh please review

**Comment by alebeta90** [comment]
@p53 I understand, ok then we need to wait for @ngoduykhanh to have it in the master branch, but good that it passed all the checks :D

I have a question, why do we receive a key_plain instead of a key that is already encoded in base64? Is just to understand the workflow, because from my point of view would be useful to have the encoded key as an answer from the api.

**Comment by p53** [comment]
@alebeta90 regarding if it can be used in production, i tried to be as much non-invasive to other PowerdnsAdmin code as possible, so this api should not affect any other functions, also i thing code quality is good, i added also tests, altough it would be good to write much more tests and also i can imagine also improving PowerdnsAdmin code generally...

**Comment by alebeta90** [comment]
@p53 I can share some of the test I did yesterday

List Zone Records

`curl -H 'Content-Type: application/json' -H 'X-API-Key: S2lWZVQ2eEFGSUxDYkd6' http://localhost:9191/api/v1/servers/localhost/zones/mydomain1.com`

Add new record

`curl -H 'Content-Type: application/json' -X PATCH --data '{"rrsets": [ {"name": "test.mydomain1.com.", "type": "A", "ttl": 86400, "changetype": "REPLACE", "records": [ {"content": "192.0.5.4", "disabled": false } ] } ] }' -H 'X-API-Key: S2lWZVQ2eEFGSUxDYkd6' http://localhost:9191/api/v1/servers/localhost/zones/mydomain1.com | jq .`

Update record

`curl -H 'Content-Type: application/json' -X PATCH --data '{"rrsets": [ {"name": "test.mydomain1.com.", "type": "A", "ttl": 86400, "changetype": "REPLACE", "records": [ {"content": "192.0.2.5", "disabled": false, "name": "test.mydomain1.com.", "ttl": 86400, "type": "A"}]}]}' -H 'X-API-Key: S2lWZVQ2eEFGSUxDYkd6' http://localhost:9191/api/v1/servers/localhost/zones/mydomain1.com | jq .`

Delete Record

`curl -H 'Content-Type: application/json' -X PATCH --data '{"rrsets": [ {"name": "test.mydomain1.com.", "type": "A", "ttl": 86400, "changetype": "DELETE"}]}' -H 'X-API-Key: S2lWZVQ2eEFGSUxDYkd6' http://localhost:9191/api/v1/servers/localhost/zones/mydomain1.com | jq .`


if you think they are useful it could be use for the readme

**Comment by ngoduykhanh** [comment]
Hi @p53 ,

Thanks for this huge contribution. It is nice to have API feature for PDA. I have some comment about this PR:

(1) API login with `API_KEY` looks good to me. However, it has some problem in the management i think:
* Why do users need to use API to mange API credentials (API keys)? I think it is better to have UI for it.
* In current design, a API key isn't mapped to a specific user. It seems to be global stuff where any other users can touch it. For instance, **Admin** creates an API then a normal **User** can delete it (by having access to a random domain).
* In my opinion, we should allow users access to the API with their credential (you already did) by default. They can also create `API keys` which have privileges same as their role.

(2) There are some debug message which isn't clear enough e.g. [this line](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/9988f8da8272f4d7a217a2c98c2a6b3e34b726ab/app/blueprints/api.py#L156)

(3) Can you rebase the commits ?

I will continue reviewing this PR and add more comment later. Thanks :-)

**Comment by p53** [comment]
1.
- first UI creation would take additional time (we can do it later), today everything is automated so why not to create API keys through API
- yes API key isn't tied to user, but is tied to domain, and user can delete only apikeys of domains to which it has access, like this we are able to deliver more granular api key scope, if we would tie it to user, any apikey of user could access any domain...
- users already can create only apikey which has same or lower role so User can create only User, Administrator all roles apikeys
2. yup i can improve debug messages
3. i will do it

**Comment by p53** [comment]
and would be good to create some diagram to have better overview of domain model, maybe today i will do it

**Comment by timja** [comment]
Any thoughts on assigning an API key to an account? this would mean if you have multiple zones you don't have to manage many API keys but only ownership of the account.

This feature looks great, for me UI isn't needed at all

**Comment by p53** [comment]
one apikey can have access to multiple zones

**Comment by ngoduykhanh** [comment]
Hi @p53 

* Yes we can do the UI later. Since PDA is a Web UI to handling the PDNS's API, i prefer having an UI to manage those keys. It is straightforward with the end-users i think. Otherwise they can use any other API gateway to do this, Kong API for example, no need PDA for this purpose :). 
* Thanks for the clarification about tying the API keys to the domain. I understand that, but not sure about the actual use case for this. There will be the requests that ask for having API keys at User/Account level soon i believe :). Same thing happened when i first implemented the user-domain mapping privileges.

**Comment by ngoduykhanh** [comment]
> 
and would be good to create some diagram to have better overview of domain model, maybe today i will do it

This would be great!

**Comment by p53** [comment]
- right for quick use UI is much more friendly
- use case is quite simple, automated application deployment responsible for it's own domain

**Comment by alebeta90** [comment]
Hello all,

Yes today it is more common to ask for api keys using the API because API services are targeted to developers. But the point from @ngoduykhanh is valid since PowerDNS-Admin was created for the UI users. Then it is important to follow that philosophy.

In facts the API implementation from @p53 is great :D im already using it and working in an Ansible Module to handle that :D

**Comment by p53** [comment]
best would be if we could separate UI from server part but that's quite big task

**Comment by p53** [comment]
@ngoduykhanh rebased and added to README how to generate ER diagram

**Comment by ngoduykhanh** [comment]
LGTM, thanks @p53 . If there is no further changes, i am going to merge this PR now.

**Comment by blakkheimgw** [comment]
Hello,

First of all, thant you for the good work on this API !

I have a question : is it possible to add the same function as it exists in the GUI, to allow auto creating reverse record (PTR) when adding an A record ? At the moment, the only solution is to give rights on the corresponding PTR zones to the user account, which is undesirable in some cases.

Regards.

**Pull request merged**
