### PR TITLE
Allow to change root domain record via dyndns

### PR DESCRIPTION
**Pull request by ssendev**
It was not possible to update `example.com`. only `foo.example.com`

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
Thanks for catching this issue. You also need to handle the `example.com` with `SOA` type unless `example.com` (A record) won't be updated.

Quic fix [here](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/7bcdc3cfd53c7e1ff186fca5775ea5289ea34d20) in another branch. cc @ivanfilippov

**Comment by ssendev** [comment]
Should i add your changes or do you just merge your branch?

**Comment by ngoduykhanh** [comment]
If my changes is ok, i will merge it by myself. Just wanna hear from @ivanfilippov since he suggested this feature and may using it.

**Comment by ivanfilippov** [comment]
@ngoduykhanh Looks good to me, this is a great addition.

Sorry for the delay in response and not being to help out @ngoduykhanh, work has been extra busy.

**Comment by ssendev** [comment]
do your changes prevent updating of AAAA records?

**Comment by ngoduykhanh** [comment]
> do your changes prevent updating of AAAA records?

Right. only IPv4 is supported. Do we have dynamic ipv6 in real use cases ?

**Comment by ssendev** [comment]
I know some people who have ipv6 at home and my router supports sending ipv6 addresses. In fact it allows sending of v4 and v6 at the same time but I am not sure there are isps who give two ips to their customers.

**Comment by joniw** [comment]
Hello,

what is the state of this PR? 

My ISP runs a dualstack environment, i get an ipv4 and an ipv6 address.

**Pull request closed without merging**
