### PR TITLE
Add LDAP_GROUP_SECURITY groupOfNames groups support (bis)

### PR DESCRIPTION
**Pull request by madmath03**
This is an updated version of PR #512 by @johnwarburton

### CODE REVIEW

**Comment by Armadill0** [comment]
Thank you so much!

@ngoduykhanh Can you have a look at that? :smile:

**Comment by ngoduykhanh** [comment]
The changes look good to me. Merged the PR. Thanks @johnwarburton and @madmath03 for the contribution.

**Comment by johnwarburton** [comment]
Thanks @ngoduykhanh and @madmath03

**Comment by garettharnish** [comment]
Agreed.  Thank you as well @ngoduykhanh and @madmath03

**Comment by madmath03** [comment]
Thanks @johnwarburton & @ngoduykhanh 😃

**Pull request merged**
