### PR TITLE
Add Active directory authentication and Timeout for large zone

### PR DESCRIPTION
**Pull request by vdchuyen**
Tested in our environment, thanks for this great frontend.

### CODE REVIEW

**Comment by onimsha** [comment]
Long time no see, @vdchuyen  :P :P

**Comment by vdchuyen** [comment]
LOL, miss u so much my dear :heart:

**Comment by onimsha** [comment]
+1 .

**Comment by ngoduykhanh** [comment]
Your changes look good to me. Pulling...Thank you for your contribution @vdchuyen .

**Pull request merged**
