### PR TITLE
History Tab Overhaul & Domain Record Modifications Changelog

### PR DESCRIPTION
**Pull request by kkmanos**
This PR is a continuation of the raised issue [#1025](https://github.com/ngoduykhanh/PowerDNS-Admin/issues/1025).

We have created a [wiki page](https://github.com/gunet/PowerDNS-Admin/wiki/Domain-Changelog-&-History-Overhaul) providing full documentation on the proposed feature.

This PR also addresses issue [#872](https://github.com/ngoduykhanh/PowerDNS-Admin/issues/872), by adding a zone-specific changelog.

Note that the Domain Changelog does not contain Reverse records that were created automatically with the `auto_ptr` setting enabled, because they do not produce a history log, as stated in issue [#1041](https://github.com/ngoduykhanh/PowerDNS-Admin/issues/1041).

### CODE REVIEW

**Comment by RGanor** [comment]
Amazing job you guys did here with the history overhaul!
Because of the amount of changes you introduce I would like the hear from the community their thought of these changes to make sure it compatible with their setup and needs.

I will test feature in the coming weekend but until then I got few points regarding this.
1) Look into lgtm alerts and fix them if possible
2) I saw that you added jqurey-ui in base.html. please add this in offline mode as well (in order to work without internet access)
3) Why you changed the Line in custom.js and commented out javascript function in user_profile.html ?

Thanks for you contribution!

**Comment by vmarkop** [comment]
@RGanor A slight mishap occured and we linked you the wrong email address. Please contact us at barbarousisk@gunet.gr instead in case you need anything. We are terribly sorry for the inconvenience.

**Comment by zoeller-freinet** [comment]
Hi @kkmanos,

thank you guys for this great work! I've yet to try out the advanced history feature, it'll come in very handy for sure.

One question on fb01274, why has `powerdnsadmin/static/assets/jquery-ui-smooth-datepicker/` been committed - shouldn't that be generated via `$ flask assets build`?

**Comment by kkmanos** [comment]
Hello @zoeller-freinet ,

We removed jquery-ui smoothness library for the datepicker. Bootstrap datepicker will now be used for the datepicker functionality. This change has been commited in a new PR #1059.


Thanks for the feedback.

**Comment by AzorianMatt** [comment]
@kkmanos do you happen to still have detailed memories of this work? I'm trying to figure out exactly what lead to merging in very broken HTML markup that I tracked back to this PR. It seems the original design used a very typical table but during this overhaul, the table was more or less stripped out in favor of tabs but much of the markup from the table was retained with a completely broken syntax.

**Comment by kkmanos** [comment]
After taking a quick look at the file changes, we utilized macros to separate components of the template into more compact templates which were re-used, resulting in a cleaner and modular code.
Aside from that, I am not able to recall any details from the changes which were made.

**Comment by AzorianMatt** [comment]
@kkmanos duly noted, thank you for the fast response!

**Pull request merged**
