### PR TITLE
Quotes fix

### PR DESCRIPTION
**Pull request by kkmanos**
Hello,

In this PR we present a fix for the issues #1064 and #1060 which have to do with the history change-log in general.

This PR is a follow up of the #1065 PR.

Thanks for the quick response from both authors of the issues and for the quick fix in PR #1065.

### CODE REVIEW

**Comment by RGanor** [comment]
It looks like I still have this error, it can parse a certain history entry:
This `history.detail` works:
```python
[2021-12-03 13:00:24,062] [admin.py:753] DEBUG - {'key': 67, 'role': 'User', 'description': 'blabla', 'domains': ['def-soa', 'bla']}
```
This entry didn't:
```python
[2021-12-03 13:00:24,062] [admin.py:753] DEBUG - {'key': 7, 'role': <Role Userr>, 'description': 'ssdor', 'domains': ['qwerty', 'com', 'testl', 'yyy', 'dd']}
[2021-12-03 13:00:24,080] [_internal.py:225] INFO - 192.168.10.254 - - [03/Dec/2021 13:00:24] "GET /admin/history_table HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration: 19

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/web/powerdns-admin/powerdnsadmin/decorators.py", line 47, in decorated_function
    return f(*args, **kwargs)
  File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 1185, in history_table
    detailedHistories = convert_histories(histories)
  File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 862, in convert_histories
    detailedHistories.append(DetailedHistory(histories[i], None))
  File "/opt/web/powerdns-admin/powerdnsadmin/routes/admin.py", line 754, in __init__
    detail_dict = json.loads(history.detail.replace("'", '"'))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 20 (char 19)
```

**Comment by kkmanos** [comment]
Hello @RGanor ,
the issue that occurred in the exception log you handed, is a different one. It should be fixed with the latest commit.
If there are any more errors regarding the history overhaul PR, then feel free to contact us at koukoularism@gunet.gr

**Comment by RGanor** [comment]
@kkmanos Can you solve the conflicts and I'll merge it ASAP

**Comment by jbe-dw** [comment]
Hello,
I have introduced a check on the 'domain_acl' key that has been renamed to domains with my last PR. This test must be kept to handle both former and new key name.

Another option could be to provide a detail message in the API functions that today generates empty message content. But this needs to be done later because the app needs a more general rework to log all actions first, and harmonize the messages in the GUI and the API.

**Comment by RGanor** [comment]
@jbe-dw so what is the correct way?
from master:
```python
""".format(detail_dict['key'], detail_dict['role'], detail_dict['description'],
						   str(accounts).replace("]","").replace("[", ""),
						   str(domains).replace("]","").replace("[", ""))
```
from this branch:
```python
""".format(detail_dict['key'], detail_dict['role'], detail_dict['description'],  str(detail_dict['domain_acl']).replace("]","").replace("[", "") if 'domain_acl' in detail_dict else "")

```

**Comment by jbe-dw** [comment]
The first one is from my last PR. There's a test just before to check for 'domain_acl' in the detail_dict's keys.
The 'domain_acl' key is not used anymore but will exist in the history.

**Comment by RGanor** [comment]
I've merge the other changes in order to fix the master.
```python
""".format(detail_dict['key'], detail_dict['role'], detail_dict['description'],  str(detail_dict['domain_acl']).replace("]","").replace("[", "") if 'domain_acl' in detail_dict else "")
```
This sadly still doesn't work for me

**Comment by kkmanos** [comment]
@RGanor  I made key access more generic, because I think your database has different keys than the current version. Let me know there is any other exception thrown.

Thanks for the feedback.

**Pull request merged**
