### PR TITLE
models refactoring

### PR DESCRIPTION
**Pull request by timfeirg**
authored by @CMGS , this commit intends to make `models.py` more pythonic

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
Thanks @CMGS and @timfeirg for your work. It looks like we have problem with user creation step in this refactoring. Password hashed isn't created after user sign up.

It was handled by this [original code](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L268)

**Comment by ngoduykhanh** [comment]
Also, have you tested with LDAP authentication? I am not sure if it won't break anything if we don't assgin user's id after create them [at this line](https://github.com/ngoduykhanh/PowerDNS-Admin/pull/125/files#diff-413e9aa8961126d20e2d90befa13e0f1L245)

**Comment by timfeirg** [comment]
fixed the password issue at [this line](https://github.com/ngoduykhanh/PowerDNS-Admin/pull/125/files#diff-413e9aa8961126d20e2d90befa13e0f1R265)

>Thanks @CMGS and @timfeirg for your work. It looks like we have problem with user creation step in this refactoring. Password hash isn't created after user sign up.

as for `self.id`, I don't think it's a problem, `self.id` is set during `__init__`, so when executing `self.create_user`, all the user attributes gets committed to the database. @CMGS had tried this out and confirmed this behavior.

>Also, have you tested with LDAP authentication? I am not sure if it won't break anything if we don't assgin user's id after create them at this line

**Comment by ngoduykhanh** [comment]
Looks  good to me now. Merging. Thanks.

**Pull request merged**
