### PR TITLE
Add API Key to the UI

### PR DESCRIPTION
**Pull request by RoeiGanor**
I recently came across the feature of API Keys. The feature was pretty hidden, under-documented, and unintuitive.
I think it will be great to add this API key feature to the UI so the admin can create/delete/update API Keys easily from the portal and not through curl or postman.

Currently, this feature is implemented exactly like the API, where only admins can create keys.
As I mention in issue #803 I think we can extend this feature of API keys even more and make it more accessible and more easily used.

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
LGTM. Thank you for your contribution. This is what I wanted to add before :-).
Merging...

**Comment by HOSTED-POWER** [comment]
Hi,


How can we use this api ? We're very interested, do you have any sample commands / documentation? :)

**Comment by RoeiGanor** [comment]
You can now create an api in the ui and associate it to domains. Then you can use the OpenAPI at /swagger to search for the api you want, and then add your key to X-API-Key header.
Like I said in the PR. this feature is really under documented, but you can use this as a reference:
https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docs/API.md

**Comment by HOSTED-POWER** [comment]
Ok thanks a lot @RoeiGanor !

One thing strange left, most api's take about 10-15 seconds to complete, this is rather long, even for simple api calls :/ :)

**Pull request merged**
