### PR TITLE
Fix issues when adding a record, and sort and/or search is involved

### LINKED ISSUE #94: Issue with add record field when sort order changed
When adding a record to a domain, if you change the sort order "highest to lowest", the entry dialogue is moved to the bottom of the list. Changing the sort order should not change where the entry dialogue is located.

Let me know if you need any more information.

### PR DESCRIPTION
**Pull request by jallakim**
Previously this caused the newly added record to either appear at the bottom, or not appear at all. Now it will always be added at the top, and whatever search present is cleared.

Fixes #94 and #115.

### CODE REVIEW

**Comment by jallakim** [comment]
Also cleaned up some of the other things (missing modal with `TODO:`, and the `<td>`-entries).

**Comment by jallakim** [comment]
Also fixed so that when adding a new record, the first text-field is focused (minimizes mouse/tab-interaction (-: ).

**Comment by jallakim** [comment]
@ngoduykhanh *notify*

**Comment by ngoduykhanh** [comment]
Looks good to me. Thanks @jallakim for this adjustment. Merging...

**Pull request merged**
