### PR TITLE
Revzones improvements

### PR DESCRIPTION
**Pull request by mikerhyner**
changed some things that are specially missing for reverse zones:
- ability to configure record types for reverse zones within config.py
- (hopefully) fixed an issue with slash in zone names caused a "404" error because our reverse zones are named like 0/p.n.n.n.in-addr.arpa (where "p" stand for subnet prefix, "n" for the upper octets)

### CODE REVIEW

**Comment by thomasDOTde** [comment]
Would you like to create an additional PR against?
https://github.com/thomasDOTde/PowerDNS-Admin

**Comment by bemanuel** [comment]
Yes, I can.
But, just when finished it?

Em sáb, 20 de jan de 2018 às 13:38, Thomas <notifications@github.com>
escreveu:

**Comment by bemanuel** [comment]
Against this ? https://github.com/thomasDOTde/PowerDNS-Admin
Or against this one? - https://github.com/ngoduykhanh/PowerDNS-Admin


Em sáb, 20 de jan de 2018 às 13:47, Bruno Silva <bemanuel.pe@gmail.com>
escreveu:

**Comment by thomasDOTde** [comment]
Aren't these features finished yet?
- ability to configure record types for reverse zones within config.py
- (hopefully) fixed an issue with slash in zone names caused a "404" error because our reverse zones are named like 0/p.n.n.n.in-addr.arpa (where "p" stand for subnet prefix, "n" for the upper octets)

**Comment by bemanuel** [comment]
I'm putting the capacity of translation, implementing Babel resources and
i18n

Em 20 de jan de 2018 13:53, "Thomas" <notifications@github.com> escreveu:

**Comment by thomasDOTde** [comment]
I thought that it requires many dependencies. Does the requirements.txt contain the bare minimum required to run Babel?

Viele Grüße
Thomas Drewermann 
- mobile access -

**Comment by bemanuel** [comment]
Yes, but i can check this again. Why is giving some error?

Em dom, 21 de jan de 2018 às 16:32, Thomas <notifications@github.com>
escreveu:

> I thought that it requires many dependencies. Does the requirements.txt
> contain the bare minimum required to run Babel?
>
> Viele Grüße
> Thomas Drewermann
> - mobile access -
>

**Comment by bemanuel** [comment]
Inclusive i'm using this one on production.

Em ter, 23 de jan de 2018 às 12:32, Bruno Silva <bemanuel.pe@gmail.com>
escreveu:

> Yes, but i can check this again. Why is giving some error?
>
> Em dom, 21 de jan de 2018 às 16:32, Thomas <notifications@github.com>
> escreveu:
>
>> I thought that it requires many dependencies. Does the requirements.txt
>> contain the bare minimum required to run Babel?
>>
>> Viele Grüße
>> Thomas Drewermann
>> - mobile access -
>>

**Comment by ngoduykhanh** [comment]
Duplicate #208 .

**Pull request closed without merging**
