### PR TITLE
Improve SAML support

### PR DESCRIPTION
**Pull request by icb-**
Accept IdP EntityID to use when metadata contains more than one IdP.
Allow specifying attribute names to get given name, surname, and email address.
Allow specifying NameIDFormat to request.
Allow specifying whether to get username from a named attribute, or NameID.
Allow getting administrator state from attribute.

All new config options default to their previous functionality if not set.

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
Thank you for your contribution. 
@thomasDOTde you might want to see this changes.

**Comment by icb-** [comment]
Is there anything you want to see different here to merge?

**Comment by icb-** [comment]
@ngoduykhanh If #130 is going to happen, would you rather see an attribute for "user role" than just a boolean for "administrator" that's currently in the PR?

**Comment by Azylog** [comment]
Hello,
This feature would really be awesome. So far, PowerDNS-Admin have templating, multi-users, one-click DNSSEC activation, almost everything needed !
I don't really understand which conflicts should be resolved to integrate this into master. May I help ?

**Comment by icb-** [comment]
@Azylog the only conflict I see is the imports in `views.py`. That's easy enough to resolve. Before merging, I would like to have support for managing which Account(s) a user belongs to from SAML assertions, which shouldn't be too difficult to add.

**Comment by ngoduykhanh** [comment]
Merged as it has been verified. Thanks again for the PR!

**Pull request merged**
