### PR TITLE
Support IDN domain

### PR DESCRIPTION
**Pull request by ngoduykhanh**
As discussed in #556 
This PR contains basic support for IDN. For now, it is just for allowing adding the IDN domain and displaying them in the pretty format.

Some more adjustment can be done:
- Allow IDN domain searching
- Display the domain name in both formats to the user

Screen Shot 2019-12-08 at 14 33 48

### CODE REVIEW

**Comment by mrsrvman** [comment]
+1.

**Comment by mrsrvman** [comment]
Please commit this request

**Comment by r-daneel** [comment]
Hi,
I rebased the code to best of my understanding here: 
https://github.com/r-daneel/PowerDNS-Admin/tree/idn-rebased

**Comment by tsabi** [comment]
+1 please commit

**Pull request closed without merging**
