### PR TITLE
Added OpenID Connect and migrated to authlib

### PR DESCRIPTION
**Pull request by chriscpritchard**
I've added an OpenID Connect tab and migrated to authlib. It works, however, there is still some more work to be done to support configuration from configuration JSON files (e.g. https://accounts.google.com/.well-known/openid-configuration) and to disable signups if a user isn't recognised as an option.

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
Thanks @chriscpritchard for submitting the PR. It looks good to me. However, just wondering why you want to set `use_reloader=False` and it is hard-coded?

**Comment by ngoduykhanh** [comment]
This pull request **introduces 4 alerts** when merging 1ffaf904b2d66e5da2fd0d0171802b347273d0b4 into a39f5c622c9c85e0b4fa6e6ac4df861e7f8e3b62 - [view on LGTM.com](https://lgtm.com/projects/g/ngoduykhanh/PowerDNS-Admin/rev/pr-b06235fdc52b3e5e39240f17e226e62f82b500b5)

**new alerts:**

* 2 for Testing equality to None
* 1 for Unused import
* 1 for Unreachable code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by chriscpritchard** [comment]
Do you need me to fix the alerts?

**Comment by ngoduykhanh** [comment]
No worries, I fixed it and merged the PR. Thanks for the contribution.

**Pull request merged**
